"""SMTP email service.

Minimal async-friendly SMTP client built on the Python standard library
(``smtplib`` + ``email.message``). Designed for low-volume transactional
emails such as approval-request notifications.

Configuration is read from ``Settings``:
    SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD,
    EMAIL_FROM, SMTP_USE_TLS (default true).

The public entry point is ``send_email``. It never raises into the
caller's main workflow — failures are reported via the return value
and the audit log.

NEVER log the password, the access token, the authorization code,
the PKCE verifier, or the Authorization header. The body itself
may contain an approval token and must therefore never be logged
verbatim — only its SHA-256[:16] fingerprint is safe to log.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
import smtplib
from email.message import EmailMessage
from typing import Optional

from backend.app.core.config import Settings, get_settings

logger = logging.getLogger(__name__)


class EmailResult:
    """Outcome of a single ``send_email`` call."""

    def __init__(self, *, success: bool, error: Optional[str] = None,
                 fingerprint_sha256_16: Optional[str] = None) -> None:
        self.success = success
        self.error = error
        self.fingerprint_sha256_16 = fingerprint_sha256_16


def _fingerprint(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _smtp_send(
    host: str,
    port: int,
    username: Optional[str],
    password: Optional[str],
    use_tls: bool,
    message: EmailMessage,
) -> None:
    """Synchronous SMTP send. Run inside ``asyncio.to_thread``."""
    if use_tls:
        with smtplib.SMTP(host, port, timeout=15) as client:
            client.ehlo()
            client.starttls()
            client.ehlo()
            if username and password:
                client.login(username, password)
            client.send_message(message)
    else:
        with smtplib.SMTP(host, port, timeout=15) as client:
            client.ehlo()
            if username and password:
                client.login(username, password)
            client.send_message(message)


async def send_email(
    *,
    to: str,
    subject: str,
    body: str,
    settings: Optional[Settings] = None,
) -> EmailResult:
    """Send one transactional email.

    Returns an ``EmailResult`` whose ``success`` flag indicates whether
    the SMTP server accepted the message. Any error is captured and
    returned — this function never raises into the caller.

    Configuration is read from ``Settings``. If SMTP is not configured
    (any of host / username / password / from is missing), the call
    short-circuits and returns ``success=False`` without attempting
    network I/O. This keeps the calling workflow (draft creation,
    approval) unaffected by missing email configuration.
    """
    cfg = settings or get_settings()

    if not (
        cfg.smtp_host
        and cfg.smtp_username
        and cfg.smtp_password
        and cfg.email_from
        and to
    ):
        return EmailResult(
            success=False,
            error="email_not_configured",
        )

    fingerprint = _fingerprint(f"{to}|{subject}|{body}")

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = cfg.email_from
    msg["To"] = to
    msg.set_content(body)

    try:
        await asyncio.to_thread(
            _smtp_send,
            cfg.smtp_host,
            cfg.smtp_port,
            cfg.smtp_username,
            cfg.smtp_password,
            cfg.email_use_tls,
            msg,
        )
    except Exception as exc:  # noqa: BLE001 — broad on purpose
        # Log the error category, never the SMTP password or message body.
        logger.warning(
            "SMTP send failed: %s",
            exc.__class__.__name__,
        )
        return EmailResult(
            success=False,
            error=exc.__class__.__name__,
            fingerprint_sha256_16=fingerprint,
        )

    return EmailResult(
        success=True,
        fingerprint_sha256_16=fingerprint,
    )


def build_approval_email_body(
    *,
    draft_title: str,
    draft_topic: str,
    approval_token: str,
    approval_url: str,
) -> str:
    """Plain-text approval-request email body.

    The approval token is included ONLY in the URL and is not printed
    anywhere in human-readable form. The token is generated by the
    existing ApprovalRepository; this helper just formats the link.
    """
    return (
        "A new LinkedIn post is waiting for your approval.\n\n"
        f"Title: {draft_title}\n"
        f"Topic: {draft_topic}\n\n"
        "Approve the post by visiting the link below. The link contains\n"
        "a single-use approval token tied to your account.\n\n"
        f"{approval_url}\n\n"
        "If you did not request this post, you can safely ignore this email.\n"
    )
