"""Reviewer Agent for LinkedIn Content Agent.

This agent reviews and improves LinkedIn posts generated by the Writer Agent.
It acts as an editor, scoring posts and improving them when necessary.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from rich.console import Console
from rich.table import Table
from models.models import LinkedInPost
from models.context_models import Context
from config.config import config
from utils.parsers import create_linkedin_post
from utils.linkedin_content import normalize_linkedin_post
from services.llm import LLMFactory


console = Console()


class DimensionScore(BaseModel):
    """Score for a specific evaluation dimension with explanation."""
    
    score: int = Field(description="Score (1-10)")
    explanation: str = Field(description="Short explanation for the score")


class ReviewScores(BaseModel):
    """Scores for different aspects of the LinkedIn post."""
    
    # Legacy scores for backward compatibility
    clarity: int = Field(description="Clarity score (1-10)")
    engagement: int = Field(description="Engagement score (1-10)")
    authenticity: int = Field(description="Authenticity score (1-10)")
    readability: int = Field(description="Readability score (1-10)")
    overall: int = Field(description="Overall score (1-10)")
    
    # New detailed dimensions
    hook_strength: Optional[DimensionScore] = Field(default=None, description="Hook strength evaluation")
    logical_flow: Optional[DimensionScore] = Field(default=None, description="Logical flow evaluation")
    professional_tone: Optional[DimensionScore] = Field(default=None, description="Professional tone evaluation")
    educational_value: Optional[DimensionScore] = Field(default=None, description="Educational value evaluation")
    credibility: Optional[DimensionScore] = Field(default=None, description="Credibility evaluation")
    cta_quality: Optional[DimensionScore] = Field(default=None, description="Call-to-action quality evaluation")
    hashtag_relevance: Optional[DimensionScore] = Field(default=None, description="Hashtag relevance evaluation")


class ReviewDecision(BaseModel):
    """Final review decision with confidence."""
    
    decision: str = Field(description="Decision: Approved, Needs Revision, or Rejected")
    confidence: str = Field(description="Confidence level: High, Medium, or Low")
    strengths: List[str] = Field(default_factory=list, description="Key strengths identified")
    weaknesses: List[str] = Field(default_factory=list, description="Key weaknesses identified")
    improvement_suggestions: List[str] = Field(default_factory=list, description="Top 3 improvement suggestions")


class ReviewResult(BaseModel):
    """Result of the review process."""
    
    original_post: LinkedInPost = Field(description="Original post from Writer Agent")
    final_post: LinkedInPost = Field(description="Final post (may be improved)")
    scores: ReviewScores = Field(description="Review scores")
    feedback: str = Field(description="Feedback on the post")
    was_improved: bool = Field(description="Whether the post was improved")
    decision: Optional[ReviewDecision] = Field(default=None, description="Detailed review decision")


class ReviewerAgent:
    """Agent that reviews and improves LinkedIn posts."""
    
    def __init__(self) -> None:
        """Initialize the Reviewer Agent."""
        # Phase 8E: prefer LLMFactory.fallback() so a runtime 429 / 404 /
        # 401 / 5xx on the first provider in the priority list
        # automatically cascades to the secondary and tertiary providers.
        self.llm = LLMFactory.fallback("reviewer")
        self._setup_prompts()

    def provider_info(self) -> dict[str, str]:
        """Return ``{"provider": ..., "model": ...}`` for the last-resolved LLM."""
        llm = getattr(self, "llm", None)
        if llm is None:
            return {"provider": "unknown", "model": "unknown"}
        return {
            "provider": getattr(llm, "provider_name", "unknown"),
            "model": getattr(llm, "model", "unknown"),
        }
    
    def _setup_prompts(self) -> None:
        """Set up prompts for reviewing and improving posts."""
        self.review_prompt = """You are an expert editor for LinkedIn content with deep expertise in professional communication.
Review the following LinkedIn post and provide a comprehensive evaluation.

THE OUTPUT MUST BE LINKEDIN-NATIVE PLAIN TEXT.
LinkedIn does NOT render any Markdown syntax. The improved post must NEVER contain:
- ## ### headings
- **bold** / __bold__ emphasis
- *italic* / _italic_ emphasis
- `inline code` backticks or ```code fences```
- Markdown tables (| --- |)
- [text](url) Markdown links (write the URL inline if needed)
- ___ / *** horizontal rules
- A "Hashtags:" footer label
- Article / document structure (numbered sections, conclusions, intro/body/conclusion layout)
- Leading-hyphen Markdown list items

The improved post must use LinkedIn-native formatting:
- Short paragraphs (1-3 lines max each), blank lines between paragraphs
- Emojis sparingly (max 2-3 per post total)
- Bullets rendered as "→ item" or "• item"
- Hashtags at the end WITHOUT a preceding label

EVALUATION DIMENSIONS (score 1-10 with explanation):

1. Hook Strength: Does the opening grab attention? Is it compelling? Does it avoid clickbait?
2. Readability: Is it easy to read? Are paragraphs short and clear? Is whitespace good for mobile?
3. Logical Flow: Do ideas transition naturally? Is there a clear structure?
4. Professional Tone: Is the tone appropriate for LinkedIn? Not too casual or formal?
5. Educational Value: Does it provide practical insights or learning?
6. Credibility: Does it sound authentic? Avoids exaggeration and clickbait?
7. Call-to-Action Quality: Is there a clear, relevant CTA? Avoids generic "Follow for more."
8. Hashtag Relevance: Are hashtags appropriate and not excessive?
9. Markdown Contamination: Is the post free of ##, **, *, _, `, |, ---? (CRITICAL — these render as raw garbage on LinkedIn)
10. Emoji Quality: Are emojis used purposefully for emphasis? (Penalize emoji-spam that looks like a teenager's first LinkedIn post)
11. Paragraph Length: Is each paragraph 1-3 lines max? (LinkedIn users read on mobile.)
12. Visual Structure: Is there blank-line separation between paragraphs, bullets, and the hashtag block?
13. CTA Quality: Is there a real, specific call-to-action that invites engagement?
14. Hashtag Quality: Are the hashtags specific to the topic (not generic filler like #motivation #success)?
15. AI-Like / Generic Writing: Does it sound like a real practitioner, or like a ChatGPT template?

LEGACY SCORES (1-10):
- Clarity: How clear and understandable is the message?
- Engagement: How likely is this to generate engagement?
- Authenticity: Does it sound genuine and not like marketing copy?
- Readability: Is it easy to read and well-structured?
- Overall: Overall quality score

FINAL DECISION:
Based on all dimensions, provide:
- Decision: Approved, Needs Revision, or Rejected
- Confidence: High, Medium, or Low
- Strengths: List 2-3 key strengths
- Weaknesses: List 2-3 key weaknesses
- Improvement Suggestions: Top 3 specific, actionable suggestions

FEEDBACK STYLE:
- Be constructive and specific
- Explain why something is good or needs improvement
- Avoid vague comments like "could be better"
- Focus on actionable feedback

POST TITLE: {title}
POST CONTENT: {content}
HASHTAGS: {hashtags}

Return your response in this format:

HOOK_STRENGTH: [score] | [explanation]
READABILITY: [score] | [explanation]
LOGICAL_FLOW: [score] | [explanation]
PROFESSIONAL_TONE: [score] | [explanation]
EDUCATIONAL_VALUE: [score] | [explanation]
CREDIBILITY: [score] | [explanation]
CTA_QUALITY: [score] | [explanation]
HASHTAG_RELEVANCE: [score] | [explanation]
MARKDOWN_CONTAMINATION: [score] | [explanation]
EMOJI_QUALITY: [score] | [explanation]
PARAGRAPH_LENGTH: [score] | [explanation]
VISUAL_STRUCTURE: [score] | [explanation]
AI_LIKE_WRITING: [score] | [explanation]

CLARITY: [score]
ENGAGEMENT: [score]
AUTHENTICITY: [score]
READABILITY: [score]
OVERALL: [score]

DECISION: [Approved/Needs Revision/Rejected]
CONFIDENCE: [High/Medium/Low]
STRENGTHS: [strength 1, strength 2, strength 3]
WEAKNESSES: [weakness 1, weakness 2, weakness 3]
IMPROVEMENT_SUGGESTIONS: [suggestion 1, suggestion 2, suggestion 3]

FEEDBACK: [2-3 sentence summary feedback]"""

        self.improve_prompt = """You are an expert editor for LinkedIn content.
Improve the following LinkedIn post while preserving the original meaning and intent.

THE OUTPUT MUST BE LINKEDIN-NATIVE PLAIN TEXT. The improved post must NEVER contain any of:
- ## ### #### headings
- **bold** or __bold__ emphasis
- *italic* or _italic_ emphasis
- `inline code` backticks or ```code fences```
- Markdown tables with | --- |
- [text](url) Markdown links (write the URL inline if needed)
- ___ or *** horizontal rules
- A "Hashtags:" footer label
- Article / document-style structure (numbered sections, intro / body / conclusion)

Use LinkedIn-native formatting:
- Short paragraphs (1-3 lines max) separated by blank lines
- Emojis sparingly (max 2-3 per post total) for emphasis
- Bullets rendered as "→ item" or "• item"
- Hashtags at the end WITHOUT a preceding label

Focus on:
- Better clarity and flow
- More engaging language (without being clickbait)
- Authentic tone
- Professional yet conversational style
- Stronger call-to-action if needed
- Removing any leftover Markdown formatting
- Better paragraph spacing

Do NOT:
- Change the core message
- Add excessive emojis
- Make it sound like marketing copy
- Exaggerate or hype
- Use a rigid template — preserve stylistic freedom
- Add a "Hashtags:" label before the hashtag list

ORIGINAL POST:
TITLE: {title}
CONTENT: {content}
HASHTAGS: {hashtags}

Return the improved post in this format:
TITLE: [improved title]
CONTENT: [improved content]
HASHTAGS: [improved hashtags]"""
    
    async def review(self, post: LinkedInPost, context: Optional[Context] = None) -> ReviewResult:
        """Review and potentially improve a LinkedIn post.

        Args:
            post: LinkedInPost from the Writer Agent.
            context: Unified context object with user preferences.

        Returns:
            ReviewResult with scores, feedback, and potentially improved post.
        """
        # Get comprehensive review
        scores, feedback, decision = await self._get_review(post)

        # Decide whether to improve based on overall score
        if scores.overall >= 8:
            final_post = post
            was_improved = False
        else:
            final_post = await self._improve_post(post)
            was_improved = True

        return ReviewResult(
            original_post=post,
            final_post=final_post,
            scores=scores,
            feedback=feedback,
            was_improved=was_improved,
            decision=decision
        )

    async def _get_review(self, post: LinkedInPost) -> tuple[ReviewScores, str, Optional[ReviewDecision]]:
        """Get review scores, feedback, and decision for a post.

        Args:
            post: LinkedInPost to review.

        Returns:
            Tuple of ReviewScores, feedback string, and ReviewDecision.
        """
        prompt = self.review_prompt.format(
            title=post.title,
            content=post.content,
            hashtags=", ".join(post.hashtags)
        )

        # The LLM is async (FallbackProvider.generate_text is a
        # coroutine). Awaiting it actually executes the call; without
        # ``await`` we'd get a coroutine object and the next line
        # (``response.text``) would fail with
        # "'coroutine' object has no attribute 'text'".
        response = await self.llm.generate_text(prompt, temperature=0.3)

        return self._parse_review_response(response.text)
    
    def _parse_review_response(self, response: str) -> tuple[ReviewScores, str, Optional[ReviewDecision]]:
        """Parse the review response from LLM.
        
        Args:
            response: Raw response from LLM.
            
        Returns:
            Tuple of ReviewScores, feedback string, and ReviewDecision.
        """
        lines = response.split('\n')
        
        # Legacy scores (backward compatibility)
        clarity = 7
        engagement = 7
        authenticity = 7
        readability = 7
        overall = 7
        feedback = "Post looks good."
        
        # New dimension scores
        hook_strength = None
        logical_flow = None
        professional_tone = None
        educational_value = None
        credibility = None
        cta_quality = None
        hashtag_relevance = None
        
        # Decision fields
        decision = "Needs Revision"
        confidence = "Medium"
        strengths = []
        weaknesses = []
        improvement_suggestions = []
        
        def extract_score(value_str: str) -> int:
            """Extract integer score from various formats (e.g., '9', '9/10', '9 out of 10')."""
            value_str = value_str.strip()
            if '/' in value_str:
                value_str = value_str.split('/')[0].strip()
            elif 'out of' in value_str.lower():
                value_str = value_str.lower().split('out of')[0].strip()
            try:
                return int(value_str)
            except ValueError:
                return 7
        
        def parse_dimension_score(line: str, key: str) -> Optional[DimensionScore]:
            """Parse dimension score in format: KEY: score | explanation"""
            if line.startswith(key + ":"):
                value_str = line.replace(key + ":", "").strip()
                if "|" in value_str:
                    parts = value_str.split("|", 1)
                    score = extract_score(parts[0])
                    explanation = parts[1].strip()
                    return DimensionScore(score=score, explanation=explanation)
            return None
        
        for line in lines:
            line = line.strip()
            
            # Parse dimension scores
            hook_strength = parse_dimension_score(line, "HOOK_STRENGTH") or hook_strength
            logical_flow = parse_dimension_score(line, "LOGICAL_FLOW") or logical_flow
            professional_tone = parse_dimension_score(line, "PROFESSIONAL_TONE") or professional_tone
            educational_value = parse_dimension_score(line, "EDUCATIONAL_VALUE") or educational_value
            credibility = parse_dimension_score(line, "CREDIBILITY") or credibility
            cta_quality = parse_dimension_score(line, "CTA_QUALITY") or cta_quality
            hashtag_relevance = parse_dimension_score(line, "HASHTAG_RELEVANCE") or hashtag_relevance
            readability = parse_dimension_score(line, "READABILITY") or DimensionScore(score=7, explanation="Default") if readability is None else readability
            
            # Parse legacy scores
            if line.startswith("CLARITY:"):
                clarity = extract_score(line.replace("CLARITY:", ""))
            elif line.startswith("ENGAGEMENT:"):
                engagement = extract_score(line.replace("ENGAGEMENT:", ""))
            elif line.startswith("AUTHENTICITY:"):
                authenticity = extract_score(line.replace("AUTHENTICITY:", ""))
            elif line.startswith("OVERALL:"):
                overall = extract_score(line.replace("OVERALL:", ""))
            elif line.startswith("FEEDBACK:"):
                feedback = line.replace("FEEDBACK:", "").strip()
            
            # Parse decision
            elif line.startswith("DECISION:"):
                decision = line.replace("DECISION:", "").strip()
            elif line.startswith("CONFIDENCE:"):
                confidence = line.replace("CONFIDENCE:", "").strip()
            elif line.startswith("STRENGTHS:"):
                strengths_str = line.replace("STRENGTHS:", "").strip()
                strengths = [s.strip() for s in strengths_str.split(",")]
            elif line.startswith("WEAKNESSES:"):
                weaknesses_str = line.replace("WEAKNESSES:", "").strip()
                weaknesses = [w.strip() for w in weaknesses_str.split(",")]
            elif line.startswith("IMPROVEMENT_SUGGESTIONS:"):
                suggestions_str = line.replace("IMPROVEMENT_SUGGESTIONS:", "").strip()
                improvement_suggestions = [s.strip() for s in suggestions_str.split(",")]
        
        # Build scores object
        scores = ReviewScores(
            clarity=clarity,
            engagement=engagement,
            authenticity=authenticity,
            readability=readability.score if isinstance(readability, DimensionScore) else readability,
            overall=overall,
            hook_strength=hook_strength,
            logical_flow=logical_flow,
            professional_tone=professional_tone,
            educational_value=educational_value,
            credibility=credibility,
            cta_quality=cta_quality,
            hashtag_relevance=hashtag_relevance
        )
        
        # Build decision object
        review_decision = ReviewDecision(
            decision=decision,
            confidence=confidence,
            strengths=strengths,
            weaknesses=weaknesses,
            improvement_suggestions=improvement_suggestions
        )
        
        return scores, feedback, review_decision
    
    async def _improve_post(self, post: LinkedInPost) -> LinkedInPost:
        """Improve a LinkedIn post based on review.

        Args:
            post: Original LinkedInPost.

        Returns:
            Improved LinkedInPost.
        """
        prompt = self.improve_prompt.format(
            title=post.title,
            content=post.content,
            hashtags=", ".join(post.hashtags)
        )

        # The LLM is async; await it so we get the actual
        # ``LLMResponse`` rather than a coroutine.
        response = await self.llm.generate_text(prompt, temperature=0.3)

        return self._parse_improve_response(response.text, post)
    
    def _parse_improve_response(self, response: str, original_post: LinkedInPost) -> LinkedInPost:
        """Parse the improved post response from LLM.

        Args:
            response: Raw response from LLM.
            original_post: Original post for fallback values.

        Returns:
            Improved LinkedInPost.
        """
        # Run the parser first to extract TITLE/CONTENT/HASHTAGS, then
        # run the canonical LinkedIn normalizer so residual Markdown
        # markers and "Hashtags: ..." leakage are removed from the
        # Reviewer's improved output too. Same pipeline as the Writer
        # — Draft Viewer and Publisher consume only the normalized form.
        parsed = create_linkedin_post(
            response, original_post, original_post.title
        )
        return normalize_linkedin_post(
            title=parsed.title,
            content=parsed.content,
            hashtags=parsed.hashtags,
        )


def print_review_result(result: ReviewResult) -> None:
    """Print review results beautifully using Rich.
    
    Args:
        result: ReviewResult to display.
    """
    console.print("\n")
    
    # Legacy scores table (backward compatibility)
    table = Table(
        title="[bold]Review Scores[/bold]",
        show_header=True,
        header_style="bold cyan",
        border_style="cyan",
        padding=(0, 1)
    )
    table.add_column("[dim]Aspect[/dim]", style="cyan", width=15)
    table.add_column("[dim]Score[/dim]", justify="right", width=10)
    
    def get_score_color(score: int) -> str:
        return "green" if score >= 8 else "yellow" if score >= 6 else "red"
    
    table.add_row("Clarity", f"[{get_score_color(result.scores.clarity)}]{result.scores.clarity}/10[/{get_score_color(result.scores.clarity)}]")
    table.add_row("Engagement", f"[{get_score_color(result.scores.engagement)}]{result.scores.engagement}/10[/{get_score_color(result.scores.engagement)}]")
    table.add_row("Authenticity", f"[{get_score_color(result.scores.authenticity)}]{result.scores.authenticity}/10[/{get_score_color(result.scores.authenticity)}]")
    table.add_row("Readability", f"[{get_score_color(result.scores.readability)}]{result.scores.readability}/10[/{get_score_color(result.scores.readability)}]")
    table.add_row(f"[bold {get_score_color(result.scores.overall)}]Overall[/bold {get_score_color(result.scores.overall)}]", f"[{get_score_color(result.scores.overall)}]{result.scores.overall}/10[/{get_score_color(result.scores.overall)}]")
    
    console.print(table)
    
    # Detailed dimensions if available
    if result.scores.hook_strength or result.scores.logical_flow:
        console.print("\n[bold cyan]═══ Detailed Evaluation ═══[/bold cyan]")
        
        dimensions = [
            ("Hook Strength", result.scores.hook_strength),
            ("Logical Flow", result.scores.logical_flow),
            ("Professional Tone", result.scores.professional_tone),
            ("Educational Value", result.scores.educational_value),
            ("Credibility", result.scores.credibility),
            ("CTA Quality", result.scores.cta_quality),
            ("Hashtag Relevance", result.scores.hashtag_relevance),
        ]
        
        for name, dim in dimensions:
            if dim:
                console.print(f"[dim]{name}:[/dim] [{get_score_color(dim.score)}]{dim.score}/10[/{get_score_color(dim.score)}] - {dim.explanation}")
    
    # Decision if available
    if result.decision:
        console.print(f"\n[bold cyan]═══ Review Decision ═══[/bold cyan]")
        decision_color = "green" if result.decision.decision == "Approved" else "yellow" if result.decision.decision == "Needs Revision" else "red"
        console.print(f"[dim]Decision:[/dim] [{decision_color}]{result.decision.decision}[/{decision_color}]")
        console.print(f"[dim]Confidence:[/dim] {result.decision.confidence}")
        
        if result.decision.strengths:
            console.print(f"\n[dim]Strengths:[/dim]")
            for strength in result.decision.strengths:
                console.print(f"  • {strength}")
        
        if result.decision.weaknesses:
            console.print(f"\n[dim]Weaknesses:[/dim]")
            for weakness in result.decision.weaknesses:
                console.print(f"  • {weakness}")
        
        if result.decision.improvement_suggestions:
            console.print(f"\n[dim]Top Improvement Suggestions:[/dim]")
            for i, suggestion in enumerate(result.decision.improvement_suggestions, 1):
                console.print(f"  {i}. {suggestion}")
    
    # Feedback
    console.print(f"\n[dim]Feedback:[/dim] {result.feedback}\n")
    
    # Improvement status
    if result.was_improved:
        console.print("[green]✓[/green] [dim]Post was improved based on review[/dim]")
    else:
        console.print("[dim]✓[/dim] [dim]Post met quality standards (no changes needed)[/dim]")
    
    console.print("\n")


if __name__ == "__main__":
    # Test the Reviewer Agent
    console.print("[bold]Testing Reviewer Agent[/bold]\n")
    
    # Create mock LinkedInPost
    mock_post = LinkedInPost(
        title="The Future of AI Agents",
        content="AI agents are changing everything. They will transform how we work. This is huge. Everyone should learn about AI agents. They are the future. AI agents will be everywhere by 2026. This is very important for developers.",
        hashtags=["#AI", "#Agents", "#Future", "#Technology"]
    )
    
    # Review the post
    agent = ReviewerAgent()
    result = agent.review(mock_post)
    
    # Print results
    print_review_result(result)
