"""Reviewer Agent for LinkedIn Content Agent.

This agent reviews and improves LinkedIn posts generated by the Writer Agent.
It acts as an editor, scoring posts and improving them when necessary.
"""

from typing import List, Dict
from pydantic import BaseModel, Field
from rich.console import Console
from rich.table import Table
from utils.models import LinkedInPost
from utils.config import config
from utils.parsers import create_linkedin_post
from tools.llm import generate_text


console = Console()


class ReviewScores(BaseModel):
    """Scores for different aspects of the LinkedIn post."""
    
    clarity: int = Field(description="Clarity score (1-10)")
    engagement: int = Field(description="Engagement score (1-10)")
    authenticity: int = Field(description="Authenticity score (1-10)")
    readability: int = Field(description="Readability score (1-10)")
    overall: int = Field(description="Overall score (1-10)")


class ReviewResult(BaseModel):
    """Result of the review process."""
    
    original_post: LinkedInPost = Field(description="Original post from Writer Agent")
    final_post: LinkedInPost = Field(description="Final post (may be improved)")
    scores: ReviewScores = Field(description="Review scores")
    feedback: str = Field(description="Feedback on the post")
    was_improved: bool = Field(description="Whether the post was improved")


class ReviewerAgent:
    """Agent that reviews and improves LinkedIn posts."""
    
    def __init__(self) -> None:
        """Initialize the Reviewer Agent."""
        self._setup_prompts()
    
    def _setup_prompts(self) -> None:
        """Set up prompts for reviewing and improving posts."""
        self.review_prompt = """You are an expert editor for LinkedIn content.
Review the following LinkedIn post and provide:

1. Scores (1-10) for:
   - Clarity: How clear and understandable is the message?
   - Engagement: How likely is this to generate engagement?
   - Authenticity: Does it sound genuine and not like marketing copy?
   - Readability: Is it easy to read and well-structured?
   - Overall: Overall quality score

2. Brief feedback (2-3 sentences) on strengths and areas for improvement.

POST TITLE: {title}
POST CONTENT: {content}
HASHTAGS: {hashtags}

Return your response in this format:
CLARITY: [score]
ENGAGEMENT: [score]
AUTHENTICITY: [score]
READABILITY: [score]
OVERALL: [score]
FEEDBACK: [feedback]"""

        self.improve_prompt = """You are an expert editor for LinkedIn content.
Improve the following LinkedIn post while preserving the original meaning and intent.

Focus on:
- Better clarity and flow
- More engaging language (without being clickbait)
- Authentic tone
- Professional yet conversational style
- Stronger call-to-action if needed

Do NOT:
- Change the core message
- Add excessive emojis
- Make it sound like marketing copy
- Exaggerate or hype

ORIGINAL POST:
TITLE: {title}
CONTENT: {content}
HASHTAGS: {hashtags}

Return the improved post in this format:
TITLE: [improved title]
CONTENT: [improved content]
HASHTAGS: [improved hashtags]"""
    
    def review(self, post: LinkedInPost) -> ReviewResult:
        """Review and potentially improve a LinkedIn post.
        
        Args:
            post: LinkedInPost from the Writer Agent.
            
        Returns:
            ReviewResult with scores, feedback, and potentially improved post.
        """
        # Get review scores
        scores, feedback = self._get_review(post)
        
        # Decide whether to improve
        if scores.overall >= 8:
            final_post = post
            was_improved = False
        else:
            final_post = self._improve_post(post)
            was_improved = True
        
        return ReviewResult(
            original_post=post,
            final_post=final_post,
            scores=scores,
            feedback=feedback,
            was_improved=was_improved
        )
    
    def _get_review(self, post: LinkedInPost) -> tuple[ReviewScores, str]:
        """Get review scores and feedback for a post.
        
        Args:
            post: LinkedInPost to review.
            
        Returns:
            Tuple of ReviewScores and feedback string.
        """
        prompt = self.review_prompt.format(
            title=post.title,
            content=post.content,
            hashtags=", ".join(post.hashtags)
        )
        
        response = generate_text(
            system_prompt="You are an expert LinkedIn content editor.",
            user_prompt=prompt,
            temperature=0.3
        )
        
        return self._parse_review_response(response)
    
    def _parse_review_response(self, response: str) -> tuple[ReviewScores, str]:
        """Parse the review response from LLM.
        
        Args:
            response: Raw response from LLM.
            
        Returns:
            Tuple of ReviewScores and feedback string.
        """
        lines = response.split('\n')
        
        clarity = 7
        engagement = 7
        authenticity = 7
        readability = 7
        overall = 7
        feedback = "Post looks good."
        
        def extract_score(value_str: str) -> int:
            """Extract integer score from various formats (e.g., '9', '9/10', '9 out of 10')."""
            value_str = value_str.strip()
            # Handle formats like '9/10', '9 out of 10', etc.
            if '/' in value_str:
                value_str = value_str.split('/')[0].strip()
            elif 'out of' in value_str.lower():
                value_str = value_str.lower().split('out of')[0].strip()
            try:
                return int(value_str)
            except ValueError:
                return 7  # Default score if parsing fails
        
        for line in lines:
            line = line.strip()
            
            if line.startswith("CLARITY:"):
                clarity = extract_score(line.replace("CLARITY:", ""))
            elif line.startswith("ENGAGEMENT:"):
                engagement = extract_score(line.replace("ENGAGEMENT:", ""))
            elif line.startswith("AUTHENTICITY:"):
                authenticity = extract_score(line.replace("AUTHENTICITY:", ""))
            elif line.startswith("READABILITY:"):
                readability = extract_score(line.replace("READABILITY:", ""))
            elif line.startswith("OVERALL:"):
                overall = extract_score(line.replace("OVERALL:", ""))
            elif line.startswith("FEEDBACK:"):
                feedback = line.replace("FEEDBACK:", "").strip()
        
        scores = ReviewScores(
            clarity=clarity,
            engagement=engagement,
            authenticity=authenticity,
            readability=readability,
            overall=overall
        )
        
        return scores, feedback
    
    def _improve_post(self, post: LinkedInPost) -> LinkedInPost:
        """Improve a LinkedIn post based on review.
        
        Args:
            post: Original LinkedInPost.
            
        Returns:
            Improved LinkedInPost.
        """
        prompt = self.improve_prompt.format(
            title=post.title,
            content=post.content,
            hashtags=", ".join(post.hashtags)
        )
        
        response = generate_text(
            system_prompt="You are an expert LinkedIn content editor.",
            user_prompt=prompt,
            temperature=0.3
        )
        
        return self._parse_improve_response(response, post)
    
    def _parse_improve_response(self, response: str, original_post: LinkedInPost) -> LinkedInPost:
        """Parse the improved post response from LLM.
        
        Args:
            response: Raw response from LLM.
            original_post: Original post for fallback values.
            
        Returns:
            Improved LinkedInPost.
        """
        return create_linkedin_post(response, original_post, original_post.title)


def print_review_result(result: ReviewResult) -> None:
    """Print review results beautifully using Rich.
    
    Args:
        result: ReviewResult to display.
    """
    console.print("\n")
    
    # Scores table
    table = Table(
        title="[bold]Review Scores[/bold]",
        show_header=True,
        header_style="bold cyan",
        border_style="cyan",
        padding=(0, 1)
    )
    table.add_column("[dim]Aspect[/dim]", style="cyan", width=15)
    table.add_column("[dim]Score[/dim]", justify="right", width=10)
    
    # Color-code scores
    def get_score_color(score: int) -> str:
        return "green" if score >= 8 else "yellow" if score >= 6 else "red"
    
    table.add_row("Clarity", f"[{get_score_color(result.scores.clarity)}]{result.scores.clarity}/10[/{get_score_color(result.scores.clarity)}]")
    table.add_row("Engagement", f"[{get_score_color(result.scores.engagement)}]{result.scores.engagement}/10[/{get_score_color(result.scores.engagement)}]")
    table.add_row("Authenticity", f"[{get_score_color(result.scores.authenticity)}]{result.scores.authenticity}/10[/{get_score_color(result.scores.authenticity)}]")
    table.add_row("Readability", f"[{get_score_color(result.scores.readability)}]{result.scores.readability}/10[/{get_score_color(result.scores.readability)}]")
    table.add_row(f"[bold {get_score_color(result.scores.overall)}]Overall[/bold {get_score_color(result.scores.overall)}]", f"[{get_score_color(result.scores.overall)}]{result.scores.overall}/10[/{get_score_color(result.scores.overall)}]")
    
    console.print(table)
    
    # Feedback
    console.print(f"\n[dim]Feedback:[/dim] {result.feedback}\n")
    
    # Improvement status
    if result.was_improved:
        console.print("[green]✓[/green] [dim]Post was improved based on review[/dim]")
    else:
        console.print("[dim]✓[/dim] [dim]Post met quality standards (no changes needed)[/dim]")
    
    console.print("\n")


if __name__ == "__main__":
    # Test the Reviewer Agent
    console.print("[bold]Testing Reviewer Agent[/bold]\n")
    
    # Create mock LinkedInPost
    mock_post = LinkedInPost(
        title="The Future of AI Agents",
        content="AI agents are changing everything. They will transform how we work. This is huge. Everyone should learn about AI agents. They are the future. AI agents will be everywhere by 2026. This is very important for developers.",
        hashtags=["#AI", "#Agents", "#Future", "#Technology"]
    )
    
    # Review the post
    agent = ReviewerAgent()
    result = agent.review(mock_post)
    
    # Print results
    print_review_result(result)
