"""Phase 8D / P3-2 — structured JSON logging for the SaaS backend.

Goals:

* Every application log line becomes a single JSON object that downstream
  tooling (log shippers, dashboards, error trackers) can parse without
  regex.
* The JSON formatter reuses the request-id ContextVar introduced by
  :mod:`backend.app.core.request_id` — no second correlation mechanism.
* Existing application behavior is preserved: loggers still use
  ``logging.getLogger(__name__)``, log calls still take a format
  string + args, ``exc_info=True`` still serializes exceptions.
* ``caplog``-based tests keep working — this module does **not** mutate
  handlers added by the test fixture.

Security schema
- The formatter does **not** collect or enrich the log record with
  request data. The only request-derived field is ``request_id``, which
  is a non-secret correlation identifier generated by the P3-1
  middleware.
- Sensitive material that should never be logged (authorization
  headers, Firebase tokens, LinkedIn tokens, OAuth secrets, approval
  tokens, cookies, passwords, MongoDB credentials, API keys, raw
  request bodies, full ``os.environ``) is the responsibility of the
  emitting code. The formatter is a passive serialiser — it does not
  introduce new collection points.

Wire-up:

* :func:`configure_json_logging` is idempotent and safe to call from the
  FastAPI lifespan or from a top-level script entrypoint. It attaches a
  single :class:`logging.StreamHandler` whose formatter is the JSON one
  defined here. Existing handlers (e.g. ``caplog``'s capture handler)
  are not touched.
* The level defaults to ``INFO`` but can be overridden via the
  ``LOG_LEVEL`` environment variable (e.g. ``LOG_LEVEL=DEBUG``).
"""

from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict


_RESERVED_LOGRECORD_ATTRS = {
    "name",
    "msg",
    "args",
    "levelname",
    "levelno",
    "pathname",
    "filename",
    "module",
    "exc_info",
    "exc_text",
    "stack_info",
    "lineno",
    "funcName",
    "created",
    "msecs",
    "relativeCreated",
    "thread",
    "threadName",
    "processName",
    "process",
    "message",
    "asctime",
    "request_id",  # populated by RequestIdLogFilter
}

#: Fields that must never be serialised as "extra" payload even if a
#: caller passed them via ``logger.info(..., extra={...})``. This is a
#: defence-in-depth allowlist; the formatter also restricts extras to
#: non-reserved keys.
_SENSITIVE_EXTRA_FRAGMENTS = (
    "authorization",
    "bearer",
    "firebase",
    "linkedin",
    "access_token",
    "refresh_token",
    "client_secret",
    "approval",
    "cookie",
    "password",
    "mongodb",
    "api_key",
    "x-api-key",
    "secret",
)


def _utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string with ``Z`` suffix."""
    now = datetime.now(timezone.utc)
    # ``isoformat(timespec='milliseconds')`` produces ``...123456+00:00``;
    # we want ``Z`` for machine-friendly parsing.
    return now.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _stringify_exception(exc_info) -> Dict[str, str]:
    """Return a JSON-safe dict describing ``exc_info``.

    The traceback is rendered through Python's standard formatter so
    that newlines/tabs are preserved as text (the outer JSON encoder
    escapes them).
    """
    if not exc_info:
        return {}
    exc_type, exc_value, exc_tb = exc_info
    type_name = exc_type.__name__ if exc_type is not None else "Unknown"
    message = str(exc_value) if exc_value is not None else ""
    # ``traceback.format_exception`` returns a list of strings — join them.
    try:
        import traceback as _tb

        formatted = "".join(
            _tb.format_exception(exc_type, exc_value, exc_tb)
        ).rstrip()
    except Exception:  # noqa: BLE001
        formatted = ""
    return {"type": type_name, "message": message, "traceback": formatted}


class JsonFormatter(logging.Formatter):
    """Format every :class:`logging.LogRecord` as a single JSON object.

    The output is always a one-line UTF-8 JSON object terminated by
    ``\\n`` so log shippers can split on newlines. Multi-line messages
    are escaped, never raw.
    """

    DEFAULT_FORMAT = (
        "%(timestamp)s %(level)s %(logger)s %(message)s"
    )

    def __init__(self) -> None:
        super().__init__(self.DEFAULT_FORMAT)

    def format(self, record: logging.LogRecord) -> str:  # noqa: A003
        # ``record.message`` is set by ``Formatter.format`` only after a
        # ``getMessage()`` call; do it explicitly so the message is
        # always the fully rendered %s string.
        record.message = record.getMessage()

        payload: Dict[str, Any] = {
            "timestamp": _utc_now_iso(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.message,
            "request_id": getattr(record, "request_id", None) or "-",
        }

        # Source-location info — useful in production but harmless to
        # expose (module/function/line).
        module = getattr(record, "module", None) or record.name.split(".")[-1]
        func = getattr(record, "funcName", None) or ""
        lineno = getattr(record, "lineno", 0) or 0
        if module or func or lineno:
            payload["source"] = {
                "module": module,
                "func": func,
                "line": lineno,
            }

        # Exception info — never raises; absent in non-error records.
        if record.exc_info:
            payload["exception"] = _stringify_exception(record.exc_info)
        if record.exc_text:
            payload.setdefault("exception", {})["formatted"] = record.exc_text
        if record.stack_info:
            payload["stack"] = record.stack_info

        # Process/thread identifiers — useful for debugging parallel
        # workers; cheap to emit.
        payload["process"] = record.process
        payload["thread"] = record.threadName

        # ``extra={...}`` payload — strip reserved attrs and obvious
        # sensitive fragments. The formatter is a passive serialiser
        # so this is a defence-in-depth filter rather than a primary
        # gate.
        extras: Dict[str, Any] = {}
        for key, value in record.__dict__.items():
            if key in _RESERVED_LOGRECORD_ATTRS or key.startswith("_"):
                continue
            if not isinstance(value, (str, int, float, bool, list, dict, type(None))):
                continue
            if isinstance(key, str) and any(
                fragment in key.lower() for fragment in _SENSITIVE_EXTRA_FRAGMENTS
            ):
                continue
            extras[key] = value
        if extras:
            payload["extra"] = extras

        try:
            return json.dumps(payload, ensure_ascii=False, default=str)
        except (TypeError, ValueError):
            # Last-resort fallback so logging never raises.
            return json.dumps(
                {
                    "timestamp": payload["timestamp"],
                    "level": payload["level"],
                    "logger": payload["logger"],
                    "message": "[unserialisable log record]",
                    "request_id": payload["request_id"],
                },
                ensure_ascii=False,
            )


#: Module-level reference so tests can verify exactly one handler is
#: attached (idempotency) and that it is the JSON one.
JSON_HANDLER_NAME = "saas_json"


def configure_json_logging(level: str | int | None = None) -> logging.Handler:
    """Attach a JSON :class:`logging.StreamHandler` to the root logger.

    Idempotent. Safe to call from the FastAPI lifespan or from a script
    entrypoint. Does **not** touch any handler that is not named
    :data:`JSON_HANDLER_NAME` — ``caplog`` and other test instrumentation
    remain intact.

    Returns the JSON handler so callers (and tests) can introspect it.
    """
    root = logging.getLogger()

    # Honour an explicit caller-supplied level, otherwise LOG_LEVEL env,
    # otherwise INFO.
    if level is None:
        level = os.getenv("LOG_LEVEL", "INFO")
    if isinstance(level, str):
        level = level.upper()
    root.setLevel(level)

    # If we already attached our handler, just re-sync the level.
    for existing in root.handlers:
        if getattr(existing, "_saas_json_marker", False):
            existing.setLevel(level)
            return existing

    handler = logging.StreamHandler(stream=sys.stderr)
    handler.setLevel(level)
    handler.setFormatter(JsonFormatter())
    handler._saas_json_marker = True  # type: ignore[attr-defined]
    handler.set_name(JSON_HANDLER_NAME)
    root.addHandler(handler)
    return handler


def reset_json_logging() -> None:
    """Remove the JSON handler from the root logger (test helper)."""
    root = logging.getLogger()
    root.handlers = [
        h for h in root.handlers if not getattr(h, "_saas_json_marker", False)
    ]


__all__ = [
    "JSON_HANDLER_NAME",
    "JsonFormatter",
    "configure_json_logging",
    "reset_json_logging",
]